import { combineReducers } from "redux";

import {
  signupSlice,
  loginSlice,
  getMeSlice,
  generateHookSlice,
  analyzeHookSlice,
  generateTitleSlice,
  analyzeScriptSlice,
  generateIdeasSlice,
  generateScriptSlice,
  getTrendingSlice,
  getDailyViralIdeasSlice,
  getStatsSlice,
  getHistorySlice,
  getAdminStatsSlice,
  getAdminUsersSlice,
  updateRoleSlice,
  updateStatusSlice,
  updateCreditsSlice,
  updateUserPlanSlice,
  getPaymentsSlice,
  createAnnouncementSlice,
  getAnnouncementsSlice,
  getAnalyticsSlice,
  getSettingsSlice,
  updateSettingsSlice,
  generateCaptionSlice,
  analyzeViralScoreSlice,
  improveCaptionSlice,
  analyzeVideoViralScoreSlice,
  generateHashtagsSlice,
  analyzeProfileSlice,
  generateFullPostSlice

} from "./apis";

const rootReducer = combineReducers({
  signup: signupSlice.reducer,
  login: loginSlice.reducer,
  me: getMeSlice.reducer,
  generateHook: generateHookSlice.reducer,
  analyzeHook: analyzeHookSlice.reducer,
  generateTitle: generateTitleSlice.reducer,
  analyzeScript: analyzeScriptSlice.reducer,
  generateIdeas: generateIdeasSlice.reducer,
  generateScript: generateScriptSlice.reducer,
  getTrending: getTrendingSlice.reducer,
  getDailyViralIdeas: getDailyViralIdeasSlice.reducer,
  getStats: getStatsSlice.reducer,
  getHistory: getHistorySlice.reducer,
  adminStats: getAdminStatsSlice.reducer,
  adminUsers: getAdminUsersSlice.reducer,
  updateRole: updateRoleSlice.reducer,
  updateStatus: updateStatusSlice.reducer,
  updateCredits: updateCreditsSlice.reducer,
  updateUserPlan: updateUserPlanSlice.reducer,
  adminPayments: getPaymentsSlice.reducer,
  createAnnouncement: createAnnouncementSlice.reducer,
  adminAnnouncements: getAnnouncementsSlice.reducer,
  adminAnalytics: getAnalyticsSlice.reducer,
  adminSettings: getSettingsSlice.reducer,
  updateSettings: updateSettingsSlice.reducer,
  generateCaption: generateCaptionSlice.reducer,
  analyzeViralScore: analyzeViralScoreSlice.reducer,
  improveCaption: improveCaptionSlice.reducer,
  analyzeVideoViralScore: analyzeVideoViralScoreSlice.reducer,
  generateHashtags: generateHashtagsSlice.reducer,
  analyzeProfile: analyzeProfileSlice.reducer,
  generateFullPost: generateFullPostSlice.reducer

});

export default rootReducer;